[package]
name = "holocron"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
base64ct = { version = "1.6.0", features = ["alloc"] }
generic-array = "0.14.7"
hkdf = "0.12.4"
ml-kem = "0.2.1"
rand = "0.8.5"
sha2 = "0.10.8"
typenum = "1.17.0"
